services:
  paybridge-gateway-svc:
    image: krakend:latest 
    container_name: paybridge-gateway-svc
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/krakend.json:/etc/krakend/krakend.json"
    command: ["/usr/bin/krakend", "run", "-d", "-c", "/etc/krakend/krakend.json"]
    networks:
      - paybridge_network
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml

networks:
  paybridge_network:
    external: true