services:
  paybridge-gateway-svc:
    image: krakend:latest 
    container_name: paybridge-gateway-svc
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/krakend.json:/etc/krakend/krakend.json"
    command: ["/usr/bin/krakend", "run", "-d", "-c", "/etc/krakend/krakend.json"]
    networks:
      - paybridge_network

networks:
  paybridge_network:
    external: true